### ISSUE TITLE
The recurring results are not as good as those mentioned in the paper

### ISSUE THREAD

**Issue by wangdeze18** [basedrhys/obfuscated-code2vec#6]
I used the type-obfuscated model, and the test datasets are from Duplicate Functions task and Author Attribution task. I encountered the following problems in reproducing:
(1) When running create_datasets.sh, an "error for method" error occurred

![2020-07-31 21-12-03屏幕截图](https://user-images.githubusercontent.com/55313414/89039300-6311cf00-d374-11ea-9427-237be8e547b8.png)

(2) When testing on the Duplicate Functions task, what kind of preprocessing method needs to be done (otherwise the relationship between the two functions cannot be judged)

![2020-07-31 21-12-53屏幕截图](https://user-images.githubusercontent.com/55313414/89039305-65742900-d374-11ea-9786-bcb3f4a3aa26.png)

(3) During the test of Author Attribution task, severe overfitting problem appeared in all kinds of Weka classifiers (all divided into one category).

![2020-07-31 21-21-55屏幕截图](https://user-images.githubusercontent.com/55313414/89039308-660cbf80-d374-11ea-8ca9-e246e129bb81.png)

![2020-07-31 21-22-10屏幕截图](https://user-images.githubusercontent.com/55313414/89039310-673dec80-d374-11ea-93fa-905719d4a30a.png)

If you can take a look, I would be very grateful.

Thank you very much!

**Comment by basedrhys** [comment]
Thanks for checking out the project! I'm sorry to see you had some trouble reproducing the results we got.

1. I'm not sure exactly what's causing this issue, I'm quite busy at the moment so it'll be a week or so before I can get onto it.
2. For the `duplicate-*` datasets, the python script should've merged the duplicate items together i.e., calculates embeddings for item `a` and `b` in the pair of (potential) duplicates, then subtracts `b` from `a` as the resulting instance in the `.arff` file. This means if `a` and `b` are **exactly** the same, the resulting instance will have all `0`s for the feature values.
3. (same response as (1))

Cheers!

**Comment by wangdeze18** [comment]
Thank you very much for your prompt answer!
I am looking forward to your continued attention.

**Comment by wangdeze18** [comment]
May I ask whether the problem has been resolved?

**Comment by basedrhys** [comment]
I've pushed some changes to the dataset pipeline which may resolve your problems. Can you please pull the most recent commits and see if this resolves your issue?

If not, can you please give instructions to reproduce the error you're getting - cheers

**Comment by wangdeze18** [comment]
I used JavaExtractor from code2vec before. The problem is still the same(；′⌒`)

**Comment by basedrhys** [comment]
Re (1) - I forgot that class constructors don't get parsed by code2vec's path extractor as there is no method name to predict. I've added a message to the logging to make this clearer.

Re (2) - In your screenshot you're using `ZeroR` - this is not a proper classifier. Using something like `SMO` on the Author Attribution task gives a normal result:

![Screenshot from 2020-08-21 14-33-45](https://user-images.githubusercontent.com/21359576/90845983-5f91c680-e3bb-11ea-9b83-6b6569d3c58a.png)

**Comment by wangdeze18** [comment]
Thank you very much. I removed the filename attribute and got the desired results with SMO.
